packages:
   - packages/*

allowBuilds:
   "@mongodb-js/zstd": true
   better-sqlite3: true
   electron: true
   esbuild: true
   lmdb: true
   msgpackr-extract: true
   msw: true
   node-liblzma: true
   protobufjs: true

onlyBuiltDependencies:
   - "@mongodb-js/zstd"
   - better-sqlite3
   - electron
   - esbuild
   - lmdb
   - msgpackr-extract
   - msw
   - node-liblzma

storeDir: .pnpm-store

minimumReleaseAgeExclude:
   - "@vercel/rust@1.4.0"
   - vercel@54.18.7
